[jenkins]
jenkins-server ansible_host=JENKINS_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/monitoring-platform-key

[monitoring]
monitoring-server ansible_host=MONITORING_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/monitoring-platform-key

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
